int soloNumeros(char num[]);
int esNumericoFlotante(char str[]);
int soloLetras(char str[]);
int alfanumerico(char str[]);
int esTelefono(char str[]);
void getString(char mensaje[],char input[]);
int getStringLetras(char mensaje[],char input[]);
int getStringNumeros(char mensaje[],char input[]);
int getStringNumerosFlotantes(char mensaje[],char input[]);
int obtenerInt(char mensaje[],char mensajeError[],char maximo[],char minimo[]);
long int obtenerDni(char mensaje[],char mensajeError[],char maximo[],char minimo[]);
long int soloNumeros_dni(char num[]);
